[package]
name = "NovaEngine"
description = "An ECS Engine"
version = "0.1.3"
edition = "2021"
license = "Apache-2.0"

[dependencies]
nova_core = { path = "nova_core", version = "0.1.0" }

[workspace]
members = [
    "nova_core",    # This is the nova_core crate
]
